# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Deploy to Dev

on:
  push:
    branches-ignore:
      - master
env:
  SERVICE_NAME: pom

jobs:
  deploy:
    name: Deploy POM to Dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_key: ${{ secrets.RUN_SA_KEY }}


    - name: Set project name
      run: |
        gcloud config set project parkplanr-dev

    - name: Build image
      run: |
        gcloud builds submit --tag gcr.io/parkplanr-dev/pom --gcs-log-dir parkplanr-dev_cloudbuild/logs

    - name: Deploy container
      run: |
        gcloud run deploy pom --image gcr.io/parkplanr-dev/pom --platform managed --region europe-north1